---
- name: "Check for ipahealthcheck_exporter binary"
  ansible.builtin.stat:
    path: "{{ ipahealthcheck_exporter_install_dir }}/ipahealthcheck-exporter"
  changed_when: false
  register: ipahealthcheck_exporter_install

- name: "Install tasks"
  when: not ipahealthcheck_exporter_install.stat.exists or ipahealthcheck_exporter_force_install|bool
  block:
    - name: "Install requierements"
      ansible.builtin.package:
        name: ["ca-certificates", "unzip", "tar", "ipa-healthcheck"]
        state: present

    - name: "Ensure install dir exists"
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - '{{ ipahealthcheck_exporter_install_dir }}'
        - '{{ ipahealthcheck_exporter_temp_dir }}'
        - '{{ ipahealthcheck_exporter_ipahealthcheck_log_path | dirname }}'

    - name: "Ensure ipahealthcheck log file exists"
      ansible.builtin.file:
        path: "{{ ipahealthcheck_exporter_ipahealthcheck_log_path }}"
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Ensure systemd override directory exists
      ansible.builtin.file:
        path: /etc/systemd/system/ipa-healthcheck.service.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "Download ipahealthcheck_exporter..."
      ansible.builtin.get_url:
        url: '{{ ipahealthcheck_exporter_url }}'
        dest: '{{ ipahealthcheck_exporter_temp_dir }}/{{ ipahealthcheck_exporter_tgz }}'
        timeout: '60'
        mode: '0644'

    - name: "Unarchive ipahealthcheck_exporter..."
      ansible.builtin.unarchive:
        src: '{{ ipahealthcheck_exporter_temp_dir }}/{{ ipahealthcheck_exporter_tgz }}'
        dest: '{{ ipahealthcheck_exporter_temp_dir }}'
        extra_opts: [--strip-components=1]
        remote_src: true
        mode: '0644'

    - name: "Copy ipahealthcheck_exporter binary..."
      ansible.builtin.copy:
        src: '{{ ipahealthcheck_exporter_temp_dir }}/ipahealthcheck_exporter'
        dest: '{{ ipahealthcheck_exporter_install_dir }}/ipahealthcheck-exporter'
        remote_src: true
        mode: '0755'

    - name: "Remove temporary directory"
      ansible.builtin.file:
        path: '{{ ipahealthcheck_exporter_temp_dir }}'
        state: absent

- name: Ensure systemd override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/ipa-healthcheck.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure ipa-healthcheck SuccessExitStatus
  ansible.builtin.copy:
    dest: /etc/systemd/system/ipa-healthcheck.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      [Service]
      SuccessExitStatus=1
  notify:
    - Reload systemd
    - Restart ipa-healthcheck

- name: "Create systemd for ipahealthcheck_exporter"
  ansible.builtin.template:
    src: 'ipahealthcheck_exporter.service.j2'
    dest: '/etc/systemd/system/ipahealthcheck_exporter.service'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart ipahealthcheck_exporter

- name: Ensure ipa-healthcheck state
  ansible.builtin.systemd:
    name: ipa-healthcheck
    state: "{{ ipahealthcheck_exporter_service_state }}"
    enabled: true

- name: Ensure ipahealthcheck_exporter state
  ansible.builtin.systemd:
    name: ipahealthcheck_exporter
    state: "{{ ipahealthcheck_exporter_service_state }}"
    enabled: true
